-- Add is_public column to vault_items if not already present
ALTER TABLE vault_items
  ADD COLUMN IF NOT EXISTS is_public boolean DEFAULT false;

-- Seed 11 recommended books as public vault items
-- Uses conditional INSERT to be idempotent

INSERT INTO vault_items (title, content_type, body, estimated_read_minutes, is_public)
SELECT 'Gut — Giulia Enders', 'book_recommendation', E'Foundation: Digestion\n\nWarren\'s note: The most accessible book ever written about the digestive system. Enders explains in plain language why your gut is your second brain — and what happens when it\'s out of balance. I recommend this to every client before their first session.\n\nKey insights: The gut-brain connection, why gut bacteria affect mood, how digestion actually works from mouth to exit.\n\nBest for: Anyone with GI symptoms, bloating, constipation, or unexplained fatigue.\n\nWhere to find it: Available at most public libraries and on Amazon.', 3, true
WHERE NOT EXISTS (SELECT 1 FROM vault_items WHERE title = 'Gut — Giulia Enders' AND is_public = true);

INSERT INTO vault_items (title, content_type, body, estimated_read_minutes, is_public)
SELECT 'Why We Get Sick — Benjamin Bikman', 'book_recommendation', E'Foundation: Blood Sugar\n\nWarren\'s note: This book changed how I think about metabolic health. Bikman — a world-class metabolic researcher — makes the case that insulin resistance is the root driver behind most chronic disease. If you deal with energy crashes, brain fog, or stubborn weight, this book explains why.\n\nKey insights: How insulin resistance develops silently, why blood sugar stability matters for every system in the body, and what dietary changes have the most impact.\n\nBest for: Clients with blood sugar imbalances, fatigue, mood swings, or metabolic concerns.\n\nWhere to find it: Available on Amazon and most major booksellers.', 3, true
WHERE NOT EXISTS (SELECT 1 FROM vault_items WHERE title = 'Why We Get Sick — Benjamin Bikman' AND is_public = true);

INSERT INTO vault_items (title, content_type, body, estimated_read_minutes, is_public)
SELECT 'The Omega-3 Connection — Andrew Stoll', 'book_recommendation', E'Foundation: Essential Fats\n\nWarren\'s note: A pioneering work on the role of omega-3 fatty acids in mental and physical health. Dr. Stoll conducted the first double-blind trials showing omega-3s could match antidepressants for mood stabilization. Required reading if you experience mood instability, brain fog, or joint inflammation.\n\nKey insights: The omega-3 to omega-6 ratio and why modern diets are deeply imbalanced, how EPA and DHA support neurotransmitter function, anti-inflammatory signaling pathways.\n\nBest for: Clients with mood challenges, neurological symptoms, or inflammatory patterns.\n\nWhere to find it: Available on Amazon and through most libraries.', 3, true
WHERE NOT EXISTS (SELECT 1 FROM vault_items WHERE title = 'The Omega-3 Connection — Andrew Stoll' AND is_public = true);

INSERT INTO vault_items (title, content_type, body, estimated_read_minutes, is_public)
SELECT 'Nourishing Traditions — Sally Fallon', 'book_recommendation', E'Foundation: Minerals\n\nWarren\'s note: This is the foundational text of the Weston A. Price movement and one of the most important books in my library. Fallon and nutritional anthropologist Mary Enig restore the wisdom of traditional food preparation — fermentation, bone broth, soaking grains, and animal fats. It reframes everything we\'ve been told about "healthy eating."\n\nKey insights: Why traditional cultures had far better mineral status than modern ones, the role of fat-soluble vitamins A, D, and K2, how to prepare foods to maximize nutrient absorption.\n\nBest for: Every client — this is foundational to understanding real food.\n\nWhere to find it: Available on Amazon. The physical book is worth owning.', 3, true
WHERE NOT EXISTS (SELECT 1 FROM vault_items WHERE title = 'Nourishing Traditions — Sally Fallon' AND is_public = true);

INSERT INTO vault_items (title, content_type, body, estimated_read_minutes, is_public)
SELECT 'Vitamin K2 and the Calcium Paradox — Kate Rheaume-Bleue', 'book_recommendation', E'Foundation: Vitamins\n\nWarren\'s note: This book answers a question that puzzled researchers for decades: why do people taking calcium supplements sometimes end up with more heart disease? The answer is vitamin K2 — the missing mineral director that tells calcium where to go. Essential reading for anyone concerned about bone health, cardiovascular health, or dental health.\n\nKey insights: The critical difference between K1 and K2, how K2 activates proteins that move calcium into bones and out of arteries, food sources of K2 and why they\'ve disappeared from the modern diet.\n\nBest for: Clients with bone density concerns, cardiovascular risk, or dental calcification.\n\nWhere to find it: Available on Amazon and most libraries.', 3, true
WHERE NOT EXISTS (SELECT 1 FROM vault_items WHERE title = 'Vitamin K2 and the Calcium Paradox — Kate Rheaume-Bleue' AND is_public = true);

INSERT INTO vault_items (title, content_type, body, estimated_read_minutes, is_public)
SELECT 'Primal Body, Primal Mind — Nora Gedgaudas', 'book_recommendation', E'Foundation: Protein\n\nWarren\'s note: Nora Gedgaudas brings together ancestral nutrition science, neuroscience, and clinical practice in a way that no other book has matched. Her work on protein quality, fat metabolism, and neurological health is directly incorporated into the ENS protocols.\n\nKey insights: How our evolutionary dietary history shapes our current nutritional needs, the role of fat as primary fuel for the brain, why adequate protein is non-negotiable for neurological function, and how carbohydrate excess drives neurodegeneration.\n\nBest for: Clients with neurological symptoms, mood disorders, or those interested in the evolutionary basis of their protocol.\n\nWhere to find it: Available on Amazon. Updated edition released 2019.', 3, true
WHERE NOT EXISTS (SELECT 1 FROM vault_items WHERE title = 'Primal Body, Primal Mind — Nora Gedgaudas' AND is_public = true);

INSERT INTO vault_items (title, content_type, body, estimated_read_minutes, is_public)
SELECT 'An Elegant Defense — Matt Richtel', 'book_recommendation', E'Foundation: Immune System\n\nWarren\'s note: A Pulitzer Prize-winning journalist follows four people navigating serious immune challenges — and in the process writes the most compelling explanation of the immune system I\'ve ever read. Richtel makes immunology accessible without dumbing it down. After reading this, you\'ll understand why foundational nutrition is always immune support.\n\nKey insights: How the immune system\'s two branches (innate and adaptive) work together, why immune dysregulation drives both autoimmune disease and vulnerability to infection, and the lifestyle factors that most influence immune calibration.\n\nBest for: Clients with autoimmune patterns, frequent illness, or inflammatory conditions.\n\nWhere to find it: Available on Amazon and at most public libraries.', 3, true
WHERE NOT EXISTS (SELECT 1 FROM vault_items WHERE title = 'An Elegant Defense — Matt Richtel' AND is_public = true);

INSERT INTO vault_items (title, content_type, body, estimated_read_minutes, is_public)
SELECT 'Why Zebras Don''t Get Ulcers — Robert Sapolsky', 'book_recommendation', E'Foundation: Adrenal/Stress\n\nWarren\'s note: Stanford neuroscientist Robert Sapolsky wrote the definitive popular science book on stress physiology — and it happens to be one of the funniest science books ever written. Understanding why chronic psychological stress is biologically so damaging is foundational to understanding adrenal dysregulation and why your body responds the way it does.\n\nKey insights: Why short-term stress is adaptive but chronic stress is destructive, how the HPA axis drives cortisol dysregulation, the connections between stress, digestion, immunity, and cardiovascular health.\n\nBest for: Any client dealing with chronic stress, adrenal fatigue, sleep disruption, or burnout.\n\nWhere to find it: Available everywhere books are sold. Third edition is the definitive version.', 3, true
WHERE NOT EXISTS (SELECT 1 FROM vault_items WHERE title = 'Why Zebras Don''t Get Ulcers — Robert Sapolsky' AND is_public = true);

INSERT INTO vault_items (title, content_type, body, estimated_read_minutes, is_public)
SELECT 'Clean — Alejandro Junger', 'book_recommendation', E'Foundation: Liver/Detox\n\nWarren\'s note: Dr. Junger\'s book demystifies detoxification — separating the legitimate science from the wellness industry noise. His clinical experience with elimination protocols maps closely to the principles behind the ENS Restoration Protocol. This is the approachable introduction to why we support the liver first.\n\nKey insights: How the liver\'s two-phase detoxification process works and what it needs to function, why the modern toxic load exceeds the liver\'s evolved capacity, practical dietary approaches to support hepatic clearance.\n\nBest for: Clients beginning an elimination or restoration protocol, or those with unexplained symptoms, skin issues, or chemical sensitivities.\n\nWhere to find it: Available on Amazon and most libraries.', 3, true
WHERE NOT EXISTS (SELECT 1 FROM vault_items WHERE title = 'Clean — Alejandro Junger' AND is_public = true);

INSERT INTO vault_items (title, content_type, body, estimated_read_minutes, is_public)
SELECT 'The Hormone Cure — Sara Gottfried', 'book_recommendation', E'Foundation: Hormones\n\nWarren\'s note: Dr. Sara Gottfried trained at Harvard and MIT and brings that rigor to functional hormone medicine. Her book is the clearest explanation I\'ve found of how to identify hormonal imbalances through symptoms before resorting to lab testing — and the nutritional and lifestyle interventions that work first.\n\nKey insights: The interconnection of cortisol, estrogen, progesterone, testosterone, and thyroid hormones, how to read your body\'s signals as a hormonal map, and the foundational nutritional steps that restore hormonal balance.\n\nBest for: Clients with hormonal symptoms — irregular cycles, mood swings, fatigue, libido changes, or perimenopausal/menopausal patterns.\n\nWhere to find it: Available on Amazon and most booksellers.', 3, true
WHERE NOT EXISTS (SELECT 1 FROM vault_items WHERE title = 'The Hormone Cure — Sara Gottfried' AND is_public = true);

INSERT INTO vault_items (title, content_type, body, estimated_read_minutes, is_public)
SELECT 'The Body Keeps the Score — Bessel van der Kolk', 'book_recommendation', E'Foundation: Mind\n\nWarren\'s note: This is the most important book I\'ve read in the last decade. Dr. van der Kolk — one of the world\'s leading trauma researchers — shows how unresolved trauma is stored in the body, not just the mind, and how it reshapes physiology over time. Understanding this transforms how we think about chronic illness, digestive dysfunction, and nervous system dysregulation.\n\nKey insights: The neuroscience of trauma and how it rewires the autonomic nervous system, why talk therapy alone is often insufficient for somatic healing, and why body-based approaches — including nutrition and movement — are essential parts of recovery.\n\nBest for: Every client. This book contextualizes why parasympathetic-first care matters.\n\nWhere to find it: Available everywhere. One of the best-selling health books of the last decade.', 3, true
WHERE NOT EXISTS (SELECT 1 FROM vault_items WHERE title = 'The Body Keeps the Score — Bessel van der Kolk' AND is_public = true);
